<Project>
  <Target Name="CopyModularGodot" BeforeTargets="CoreCompile">
    <PropertyGroup>
      <ModularGodotSource>$(MSBuildThisFileDirectory)..\content</ModularGodotSource>
      <ProjectRootDir>$(ProjectDir)ModularGodot</ProjectRootDir>
    </PropertyGroup>

    <!-- Get all files from the source addons directory -->
    <ItemGroup>
      <ModularGodotSourceFiles Include="$(ModularGodotSource)\**\*" />
    </ItemGroup>

    <!-- Copy files preserving directory structure -->
    <Copy
      SourceFiles="@(ModularGodotSourceFiles)"
      DestinationFiles="@(ModularGodotSourceFiles->'$(ProjectRootDir)\%(RecursiveDir)%(Filename)%(Extension)')"
      SkipUnchangedFiles="true"
      Condition="Exists('$(ModularGodotSource)')"
    />
  </Target>
</Project>
