name: Run Tests

on:
  push:
    branches: [ "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore src/ModularGodot.Core.sln
    - name: Build
      run: dotnet build src/ModularGodot.Core.sln --no-restore
    - name: Test
      run: dotnet test src/ModularGodot.Core.Test/ --no-build --verbosity normal
